# Generated by Django 5.2.17 on 2026-08-24 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0081_alter_race_bot_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'subject'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_external_provider_subject'), models.UniqueConstraint(fields=('provider', 'user'), name='unique_external_provider_user')],
            },
        ),
    ]
