# Generated by Django 5.2.17 on 2026-08-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetime', '0082_externalidentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='goal',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position of this goal in goal lists and leaderboards. Lower numbers appear first; goals sharing a number are ordered by name.'),
        ),
    ]
